### ISSUE TITLE
Seperate Interfaces to Contract project to provide abstraction layer

### ISSUE THREAD

**Issue by harrypooni** [jbogard/MediatR#1014]
Move interfaces away from implementation provides flexibility when projects are separated in consumer code base.

**Comment by Mayron** [comment]
To add to this, I was thinking today whether it would be possible to have `IRequestHandler` in another package (or in the `MediatR.Contracts` package if that's possible (probably not, I'd guess). 

The reason is because I have a `Presentation` layer of my architecture that uses `IMediator` to send requests, and the handlers are in a different project, as part of the `Application` layer, and implement `IRequestHandler`. But I want to avoid being able to inject `IMediator` into those handlers to prevent handlers sending out more requests.

I wish the handlers didn't have a reference to `IMediator` because I think it would solve this issue. They only need `IRequestHandler` but that's not in the Contracts package unlike `IRequest`. I found this a bit unusual.

**Comment by khellang** [comment]
Physically separating types to enforce architectural styles sound like a slippery slope. What you're requesting sounds like a few types per assembly, which seems excessive. Why don't you write some architecture tests or a Roslyn analyzer to enforce your requirements instead?

> Is this something that could be done in a way that's backwards compatible with previous versions of MediatR?

No, the old assembly/package would need to still reference the new assembly/package and apply a [`TypeForwardedToAttribute`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.typeforwardedtoattribute?view=net-8.0) in order to make it backwards compatible, but that seems to defeat your requirement(s).

**Comment by harrypooni** [comment]
Any objections to the pr being approved?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Mayron** [comment]
@harrypooni I would very much appreciate just one other project containing the abstractions for IMediator and ISender instead of including them in the Contracts project because this would solve my issue mentioned above. The issue with sending nested requests inside handlers has been mentioned a number of times on previous issues and blogs/posts across the internet, and having this other project is a very simple change, especially since you've already done most of the work in this PR.

**Comment by Mayron** [comment]
Also, a software component is often designed with required interfaces and provided interfaces. It is quite common for these interfaces to be placed in two separate abstraction projects. The required interfaces have an implementation contained within the component. These are input interfaces used to communicate indirectly with the component (e.g., the IMediator). The provided interfaces (e.g. the ones contained in the current Contracts project) are ones that we can provide implementations of. For example, a custom application request or handler that implements IRequest/IRequestHandler.

This design is not unusual and is quite common in many architectures I have worked on, so I don't think my request is unusual and actually provides a lot of flexibility and encapsulation benefits.

**Comment by Mayron** [comment]
You could also keep IMediator and ISender in the MediatR project as a temporary measure, but I appreciate the original issue of keeping abstractions away from the implementation project, which is why I'd suggest 2 abstraction projects.

**Comment by Mayron** [comment]
I created a new PR to solve an issue with the initial one, and to implement the design I mentioned above:
https://github.com/jbogard/MediatR/pull/1020

**Comment by jbogard** [comment]
I'm not splitting packages or projects out any further for any opinionated code architectural styles. There are better, more effective ways to solve these problems that also don't involve myself having to maintain even more packages.

The current packages are split ONLY because disparate applications often need to reference a "contracts" project in teams where that contracts are things like API DTOs. The separate Contracts package removes a "diamond dependency" on MediatR.
