### ISSUE TITLE
How do I register INotification with generics?

### ISSUE THREAD

**Issue by grosch-intl** [jbogard/MediatR#1024]
Is there any way to use notifications with generics?  I have this:

```csharp
public sealed record ApprovedNotification<T>(T Checklist) : INotification 
    where T : IChecklist;

public sealed class NotificationHandler<T> : INotificationHandler<ApprovedNotification<T>>
    where T : IChecklist
```

When I send the notification, the handler is never called.  I'm guessing I need to do some type of explicit registration?

**Comment by MattWood21** [comment]
You can use generics out of the box in almost the same way:

``` csharp
public record ApprovedNotification<T>(T Checklist) : INotification
    where T: IChecklist;

public sealed class NotificationHandler<T> : INotificationHandler<T>
    where T : ApprovedNotification<IChecklist>
{
    public Task Handle(T notification, CancellationToken cancellationToken)
    {
        Console.WriteLine("Handled");
        return Task.CompletedTask;
    }
}
```

The differences:

- The notification type can't be sealed due to boxing/unboxing constraints
- The handler needs to the type of the notification, not the type inside the notification, though you can specify that it handles only notifications of the specified type you're looking for

**Comment by grosch-intl** [comment]
Thank you, @MattWood21 !
