### ISSUE TITLE
Firing different handlers using a single request

### ISSUE THREAD

**Issue by AlonAm** [jbogard/MediatR#111]
I have a use case where i want to fire different handlers using a single request object.
not all handlers at the same time (like notifications), but a different handler each time.

not sure (yet) if and how to achieve that with MetiatR.

for example, i have an Item object that contains the data and i use a custom pipeline (not through mediatr) to specify the type of handler that should handle it:

`_mediator.Send(item, typeof(IHandlerOfSomeKind<>));`

in another call

`_mediator.Send(item, typeof(IHandlerOfSomeOtherKind<>));`

I know this is awkward since the caller knows something about the receiver but still i'm looking for a clean way to achieve that.

another requirement is that i need to know whether the request object supports the desired handler (functionality).

for example:

`public class Item : ICanOpenInBrowser, ICanDoSomethingElse`

`_mediator.Send(item, typeof(IOpenInBrowser<>));`
`_mediator.Send(item, typeof(IDoSomethingElse<>));`

suggestions?

**Comment by no1melman** [comment]
I dunno, personally I would prefer the current behaviour because with your request behaviour it wouldn't be obvious or easy to reason about the system. If you need to fire off two handlers due to one request then do so, I wouldn't necessarily see the point to do otherwise. That is just my perception...
