### ISSUE TITLE
ComponentNotRegisteredException without having IRequestHandler

### ISSUE THREAD

**Issue by binoypatel** [jbogard/MediatR#130]
Hi there,

I am using MediatR (v 3.0) with Autofac in ASP.Net Core project. I have sample code at https://github.com/binoypatel/AutoFac.Mediatr.Lab. In this project I have commented following line in MediatorModule.cs file:

`//builder.RegisterGeneric(typeof(GenericQueryRequestHandler<>)).As(typeof(IRequestHandler<,>));`

What is interesting is, autofac is throwing ComponentNotRegisteredException when above line is commented. In my real project, I don't have any handler that implements IRequestHandler. This was working in v 2.10. Hitting continue button in debug mode, continue loading the application but is there a better way to deal with this situation?

Thanks,
Binoy

**Comment by vegar** [comment]
I hit the same issue when upgrading to 3.0, and I'm using LightInject.

I think this is more of a problem with the way we choose to implement `SingleInstanceFactory` then the way `MediatR` works.  Since `MediatR` changed the whole `IRequest<>` vs `IAsyncRequest<>` thing - to the better, I must say - it will now first look for a synchronous handler and then for an asynchronous handler. 

In my case, I implemented the `SingleInstanceFactory` as 

```
container.Register<SingleInstanceFactory>(fac => t => fac.GetInstance(t));
```

Since it in no synchronous handler (as long as the example line is commented out) `GetInstance` will throw an exception - [which `MediatR` catches](https://github.com/jbogard/MediatR/blob/master/src/MediatR/Internal/RequestHandler.cs#L12-L19) and returns null. 

If I change my implementation to 

```
container.Register<SingleInstanceFactory>(fac => t => fac.TryGetInstance(t));
```

`LightInject` will itself return null instead of throwing exception, and - voila - problem be gone!


I don't know `AutoFac`, but according to [documentation](http://docs.autofac.org/en/latest/resolve/), they too have a `TryResolve` to match the exception-throwing `Resolve`.

**Comment by jbogard** [comment]
I updated the examples to use the TryXyz methods as much as possible.
