### ISSUE TITLE
Publish notifications casted to INotification does not work

### ISSUE THREAD

**Issue by Veikedo** [jbogard/MediatR#133]
// it works
            var concrete = new QuestionAnswered();
            await _mediator.Publish(concrete);

            // it does not
            INotification underlying = new QuestionAnswered();
            await _mediator.Publish(underlying);

The platform is asp.net core.
I have domain entities with properties like this one:
`public IEnumerable<INotification> Events => _events;`
which are published when `.SaveChanges()` called.

as a workaround use `dynamic`

                foreach (dynamic message in entry.Events)
                {
                    await _mediator.Publish(message).ConfigureAwait(false);
                }

**Comment by dvanherten** [comment]
This was fixed by #124 and has been pulled in.  I do not believe a new version that contains the fix has been pushed up to Nuget yet.  

In the meantime, you can grab the current master branch and stick the project in your aspcore src folder.  The project.json reference will use the updated code because it exists in your src folder. (provides a warning that it's not using the version you specified as a reminder this will be temporary so you don't forget.

When a new nuget package becomes available you can just delete the Mediatr code you pulled down and update the project.json reference. 

I'm currently doing this to get around the issue so I don't have to adjust my calling code to compensate.

**Comment by Veikedo** [comment]
@dvanherten thanks for the reply
