### ISSUE TITLE
Question: How to return data from command

### ISSUE THREAD

**Issue by denisz1** [jbogard/MediatR#141]
When creating new entity, using REST principles, must return 201/Created response, with "Location" header pointing to url for new resource, which is usually "details" view for new entity. In ASP.NET can do this easily by returning `CreatedAtAction()` or `CreatedAtRoute()` from action.

Problem is Mediatr command handler has one of this:

    void Handle(TRequest message);
    Task Handle(TRequest message);

So I can send command from controller "create" action, and in handler I create new entity.

*BUT, handler returns void.* We need new entity PK, not void. So cannot do redirect to details view.

Is some way to do this?

Thanks for great library!

**Comment by sq735** [comment]
Hope, this is example helps you.

```
public class Pong
{
        public string Message { get; set; }
}
```

```
public class PingRequestAsync : IRequest<Pong>
{
        public string Message { get; set; }
}
```

```
public class PingAsyncHandler : IAsyncRequestHandler<PingRequestAsync, Pong>
{
        public Task<Pong> Handle(PingRequestAsync message)
        {
		return Task.FromResult(new Pong { Message = message.Message + " Pong" });
        }
}
```
Usage

`var response = await mediator.Send(new PingRequestAsync { Message = "Ping" });`

**Comment by denisz1** [comment]
@sq735 Interesting... So you are saying that to instead treat command like a query?

**Comment by sq735** [comment]
@denisz1, Exactly. "Mediator" doesn't has interfaces that represent "query", instead of this, "Mediator" has two interfaces:

[IRequest](https://github.com/jbogard/MediatR/blob/master/src/MediatR/IRequest.cs#L6) - marker interface to represent a request with a void response.

[IRequest{TResponse}](https://github.com/jbogard/MediatR/blob/master/src/MediatR/IRequest.cs#L12) - marker interface to represent a request with a response, where TResponse Response type

**Comment by denisz1** [comment]
Oh ok so for Mediatr "command" and "query" is just arbitrary concept. In fact they both treat the same, as "request".

Thanks.

(BTW there is another way to return data, by making it property in the command. But your way is better.)
