### ISSUE TITLE
Define separate dependencies for the netstandard1.1 version instead of using "NETStandard.Library": "1.6.0"

### ISSUE THREAD

**Issue by StefH** [jbogard/MediatR#147]
Maybe better to just list the dependencies you need instead of using `"NETStandard.Library": "1.6.0"` ?

**Comment by jbogard** [comment]
The recommendation from the MS team is to define your dependencies against NetStandard.Library. I don't remember exactly why, but that's what they recommended.

**Comment by kappy** [comment]
Do you know more about that recomendation? Because one thing I noticed is that when you try to reference a project with only NetStandard.Library (without the dotnet45 like mediatR has) you get a lot of assemblies refereced, even if you don't actually need them.

Adding the dotnet45 for better supporting the apps with the Full framework, the reference seems pretty good like it was before .net core but you kinda loose the ability to run tests on linux (for example) without having mono installed

**Comment by StefH** [comment]
@jbogard Personally I try to build all my NETStandard libraries with as minimum dependencies as possible.

@kappy Good point, however we still need 4.x or 4.5

**Comment by jbogard** [comment]
@kappy wait, MediatR DOES have net45 defined. I'll ping the .NET team, I had read it a year ago or so but now can't find it.

What issues is this causing you?

**Comment by kappy** [comment]
@jbogard it does, and that's why I can't compile it or run the tests on an ubuntu (for example) machine without mono installed. 

Btw, why do you define the net45? the netstandard 1.1 is already compatible with the .Net Framework 4.5, despite the behaviour I described earlier that causes a lot of dependencies being attached

**Comment by jbogard** [comment]
Old nuget clients don't recognize netstandard1.1

**Comment by jbogard** [comment]
Welp, it looks like they don't recommend just using the catch-all package anymore:

https://twitter.com/terrajobst/status/837684989957300224

**Comment by remcoros** [comment]
Here's a description on how to reduce dependencies (by checking/copy/paste from project.lock.json): https://github.com/dotnet/docs/blob/master/docs/core/deploying/reducing-dependencies.md

**Comment by StefH** [comment]
@jbogard some updates to do ... ;-)

@remcoros nice link. (However I still just select the dependencies manually...)

**Comment by StefH** [comment]
@jbogard some updates to do ... ;-)

@remcoros nice link. (However I still just select the dependencies manually...)
