### ISSUE TITLE
Pipeline doesn't execute for IRequest

### ISSUE THREAD

**Issue by no1melman** [jbogard/MediatR#166]
I've just been playing around with the new pipeline behaviours. I setup up my structuremap config like so:

```
    var container = new Container();

    container.Configure(c =>
    {
        c.Scan(scanner =>
        {
            scanner.TheCallingAssembly();
            scanner.AssemblyContainingType<IMediator>();
            scanner.WithDefaultConventions();
                    
            scanner.ConnectImplementationsToTypesClosing(typeof(IRequestHandler<,>));
            scanner.ConnectImplementationsToTypesClosing(typeof(IAsyncRequestHandler<,>));
            scanner.ConnectImplementationsToTypesClosing(typeof(IRequestHandler<>));
            scanner.ConnectImplementationsToTypesClosing(typeof(IAsyncRequestHandler<>));
            scanner.ConnectImplementationsToTypesClosing(typeof(ICancellableAsyncRequestHandler<,>));
            scanner.ConnectImplementationsToTypesClosing(typeof(ICancellableAsyncRequestHandler<>));

            scanner.ConnectImplementationsToTypesClosing(typeof(IValidator<>));
        });
                
        c.For(typeof(IPipelineBehavior<,>)).Add(typeof(ValidationPipelineBehaviour<,>));
                
        c.For<SingleInstanceFactory>().Use<SingleInstanceFactory>(ctx => t => ctx.GetInstance(t));
        c.For<MultiInstanceFactory>().Use<MultiInstanceFactory>(ctx => t => ctx.GetAllInstances(t));
    });

    return container;
```

And I noticed, when my request implements `IRequest` it doesn't execute the `ValidationPipelineBehaviour`, however when I change it to `IRequest<Unit>` it does.

I don't know if this is a known issue - or whether this is intended behaviour?

**Comment by jbogard** [comment]
Is there anything different with the sample app from your config?

**Comment by janno-p** [comment]
Hi!

Make sure you don't have type constraints declared in your ValidationPipelineBehavior class. I had same issue with almost identical StructureMap setup, and the reason it failed was because I had declared my ValidationPipelineBehavior class as follows:

```
public class ValidationPipelineBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
    where TRequest : IRequest<TResponse>
{
```

Removing the `where ...` part made this pipeline behavior available to `IRequest` types too (which is reasonable, since `Unit` cannot possibly be related to my custom types).

**Comment by no1melman** [comment]
Do you really want to remove the generic constraint?

**Comment by janno-p** [comment]
In my case the type constraint came from `ValidationHandler` type which I used as decorator before replacing it with pipeline type. `ValidationHandler` was implementing `IRequestHandler<,>` which forced me to use that particular generic constraint and it remained there when I refactored it to pipeline type.

Pipeline does not require that constraint, and to be more precise, using the constraint actually causes IRequest messages to be ignored from that pipeline. In my case the generic constraint `where TRequest : IRequest<TResponse>` cannot work for types implementing `IRequest` because `IRequest` does not implement generic `IRequest<>` in any form at the moment.

It would work if `IRequest` was defined as `interface IRequest : IRequest<Unit>`, but currently it is not, so in my case the solution was to remove generic constraint from pipeline definition.

**Comment by jbogard** [comment]
I have no idea why I took that interface inheritance away.

**Comment by no1melman** [comment]
Do you want it back in, could open a PR?

**Comment by jbogard** [comment]
Not sure what the impact would be tbqh, shouldn't be a very big change.

**Comment by jbogard** [comment]
I just made the change, doesn't seem like it was a big deal (I started outputting all the results).
