### ISSUE TITLE
Cross-Cutting Concerns via Message Headers

### ISSUE THREAD

**Issue by jkodroff** [jbogard/MediatR#20]
I have a [similar project](https://github.com/jkodroff/SeptaBus) that has some support for cross-cutting concerns (date-time stamp, current user, current user's roles) which you can check out [here](https://github.com/jkodroff/SeptaBus#decorators).

Any interest in rolling those capabilities into MediatR?  I'm aware my implementation for users/roles is for old crappy Membership, but I could create an implementation for Membership and ASP.NET Identity.

As far as I know, it would require some concrete classes in order to add headers to the messages.  If there's some other way to do it, let me know (assuming you're into it).

**Comment by jbogard** [comment]
No - not because I don't do this on every project, but because I'd personally rather document how you can build your own pipeline rather than I supply it myself.

I could go that route, and I thought about it, but those thing are hard, and I wanted to try to keep MediatR's scope as small as possible, does that make sense?

**Comment by jkodroff** [comment]
Sorry for the slow reply.  That's cool.  I might consider doing it as an extension package, especially if I adopt MediatR on my own project (assuming that's cool with you).
