### ISSUE TITLE
Subscribe a notification in runtime

### ISSUE THREAD

**Issue by luboshl** [jbogard/MediatR#208]
Hi,

is there a way how to (un)subscribe a notification in runtime?

**Comment by luboshl** [comment]
You mean to delete the class? What I meant was to be able create handler in runtime, so to create new instance of some class and to add it to the Mediator. I took a look into the Mediator class and now I understand that this is not possible. All handlers are resolved by factories given by the constructor.

To be able to add subscriptions in runtime, there should be something like
```
public void Subscribe<T>(NotificationHandler handler)
{ 
    _notificationHandlers.Add(typeof(T), handlerr);
}
```

**Comment by paulvanbladel** [comment]
@luboshl are you trying to do the domain event pattern as in the spirit of
https://lostechies.com/jimmybogard/2014/05/13/a-better-domain-events-pattern/ ?
If so, that's possible with mediatR.

**Comment by luboshl** [comment]
@paulvanbladel what I mean is something different - just to be able to add a subscription to an event dynamically in runtime. For example to add a delegate to handle the event or to add an instance of a handler (as in my previous post).

But after my first question I took a look into implementation of the MediatR, so I understand this is case that is not implemented here.

**Comment by puppetSpace** [comment]
I'm looking for the same thing.  I just want to subscribe an instance to certain events. But I guess this does not work in Mediatr since it creates new instance of a handler when a request is made.

The reason I need it: I have a sidebar which contains items. and I have a page where I can create a new item of that data. These are 2 separate components on my view.
When I create a new item, I send my request and the handler does it's business logic and inserts it into the database. But now I want to notify my sidebar component that a new item is created. I thought that I could use the notifications from Mediatr. 

It would be cool if I could just implement INotificationHandler<TE> on my sidebar component and use like IMediator.Subscribe(this) in the constructor. And whenever a notification of TE gets published, the Sidebar's Handle method would be called. using the instance added by IMediator.Subscribe(this) instead of creating a new instance.

**Comment by jbogard** [comment]
I think you’ll just want to create your own thing for this. It’s not what
MediatR was designed for.

**Comment by StevenRasmussen** [comment]
Thought I'd put this out there... just published a project that solves this problem in a way that uses the MediatR concepts so that you can dynamically add/remove notification handlers.  For anyone interested the project is located [here](https://github.com/StevenRasmussen/MediatR.Dynamic)
