### ISSUE TITLE
Nuget package doesnt include the SingleInstanceFactory/MultipleInstanceFactory delegates

### ISSUE THREAD

**Issue by sachabarber** [jbogard/MediatR#28]
I wanted to use this, and for some reason the SingleInstanceFactory/MultipleInstanceFactory delegates are not included in the Nuget package, I have verified that by using Object Browser, and making sure I am looking in right namespace by downloading the code directly from GitHub.

They just aint in the Nuget package. Nuget package I used was v1.0.0.0

Can this please be fixed

**Comment by jbogard** [comment]
They're not because they're in the 2.0 beta package. Never were in the 1.0 codebase.

**Comment by sachabarber** [comment]
Fair enough, I guess you will update your blog post showing usage once 2.0 code Nuget packae in no longer BETA then.

I have made it work with WindsorServiceLocator for now.

**Comment by jbogard** [comment]
The package is beta because it supports ASP.NET vNext, along with a dozen other platforms. vNext is pre-release, and NuGet (ugh) forces you to mark your package as pre-release if any *one* of the supported platforms has a pre-release package dependency. I'm trying to find a workaround but so far the only one is to create two packages, and that is more confusing because there's no upgrade path in NuGet once I recombine the packages. It's "beta" because I had to label it that way. It's 2.0 in all other respects.

And what blog post? A new post?

**Comment by sachabarber** [comment]
Sorry I was being a retard, what I meant was would you be covering the new 2.0 stuff in a post, but you are already.

I am new to this package, but may have been nice to see example of 1.0.0.0 and 2.0.0.0 covered in readme.

Still all good now, mine works now. Good stuff.

I wrote my own mediator a while ago, using attributes for finding handlers.
