### ISSUE TITLE
Problem when I try to use INotification

### ISSUE THREAD

**Issue by biosid** [jbogard/MediatR#282]
When I call  _mediator.Publish(command) to publish INotification object, my notification handler calls several times. 
But when I use IRequestHandler, IRequest and _mediator.Send(command) insted of INotification, and INoficationHandler, everything works fine.

**Case**
Handler.cs
```
public class CreateEventCommandHandler : INotificationHandler<CreateEventCommand>
    {
...
        public CreateEventCommandHandler(IEventTaskService taskService, 
IHubContext<EventsHub> hubContext)
        {
 ...
        }

        public async Task Handle(CreateEventCommand cmd, CancellationToken cancellationToken)
        {
            var item = cmd.Adapt<Event>();
          ....
        }
    }
```
NotificationHandler.cs
```
  public class CreateEventCommand : INotification
    {
       ...
    }
```
AutofacModule.cs

...
  base.Load(builder);

            // enables contravariant Resolve() for interfaces with single contravariant ("in") arg
            builder
                .RegisterSource(new ContravariantRegistrationSource());

            // mediator itself
            builder
                .RegisterType<Mediator>()
                .As<IMediator>()
                .InstancePerLifetimeScope();

            // request handlers
            builder
                .Register<ServiceFactory>(ctx =>
                {
                    var c = ctx.Resolve<IComponentContext>();
                    return t =>
                    {
                        object o;
                        return c.TryResolve(t, out o) ? o : null;
                    };
                })
                .InstancePerLifetimeScope();
```
  builder.RegisterAssemblyTypes(typeof(CreateEventCommand).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(INotificationHandler<>));

            builder.RegisterAssemblyTypes(typeof(StatusChangeCommand).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(INotificationHandler<>));

          builder.RegisterAssemblyTypes(typeof(DiscussionStatusChangeCommand).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(INotificationHandler<>));
```
    <PackageReference Include="MediatR" Version="5.0.1" />
    <PackageReference Include="Autofac" Version="4.8.1" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.2.2" />

**Comment by bartosz6** [comment]
I'm lost after trying to understand purpose of this line 
`public class CreateEventCommandHandler : INotificationHandler<CreateEventCommand>`
What are you trying to achieve? 1 request = 1 handler, 1 notification = multiple handlers, why would you want to use notification handler for commands?

About multiple notification handler hits - its problem with your container configuration.
`  builder.RegisterAssemblyTypes(typeof(CreateEventCommand).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(INotificationHandler<>));
            builder.RegisterAssemblyTypes(typeof(StatusChangeCommand).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(INotificationHandler<>));
builder.RegisterAssemblyTypes(typeof(DiscussionStatusChangeCommand).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(INotificationHandler<>));`
Here you are using some random command to get assembly, which is pretty bad approach, then you declare **every** class that implements INotificationHandler to be injected as this interface. You are doing it 3 times. Because **request** handler is resolved by getting first registered type and **notification** handler by getting all registered types you end up with your notification handlers being called multiple times (I bet it's 3 times ;) ).
