### ISSUE TITLE
When using Unit

### ISSUE THREAD

**Issue by EynsherKiel** [jbogard/MediatR#311]
Hello!

On my work have opinion, that struct Unit using for sinchronization mediatr and always need use Unit.Value. Then I have 2 questions

1) Unit using for sinchronization?
2) Unit.Value and default(Unit) is equels datas? I need always return Unit.Value or just in 7.1 return default?

**Comment by jbogard** [comment]
Ohhhhh good question! Unit isn't a struct, so I don't think you can return
"default", that would be null. It would be nice to have a way to be able to
do that.

Synchronization? Can you elaborate?

**Comment by EynsherKiel** [comment]
Thank for you answer!

Unit is struct : https://github.com/jbogard/MediatR/blob/c1ad66ef52434a22c10a0de5e060d13b185ef80b/src/MediatR/Unit.cs

`public struct Unit : IEquatable<Unit>, IComparable<Unit>, IComparable`

**Comment by EynsherKiel** [comment]
About synchronization I self dosn't know )

**Comment by jbogard** [comment]
Oh ha it is! Whoops! Yes default(Unit) could work. I can't believe I missed
this!

**Comment by EynsherKiel** [comment]
And so. 

My collegies thinking that Unit using for synchronization request calls. And with this statement need always return Unit.Value. But I don't understand how simple struct may using for sinchronization. Unit.Value be copied inside return, though is it static.

What are you say on this?

**Comment by jbogard** [comment]
Do you mean Synchronous request calls?

**Comment by EynsherKiel** [comment]
Maybe )

**Comment by jbogard** [comment]
Oh and in C# 7.1 you can just do `return default;`

The `IMediator` interface is async-only - this is because I needed to avoid sync and async pipelines.

For synchronous request handlers, you can either:

- Implement `IRequestHandler` and `return default;`
- Inherit `RequestHandler` and override `void Handle`

I made abstract helper classes for cases where you don't want to return `Unit` or don't need async. It's still async at the caller level though, just like ASP.NET Core's filters, actions etc.

**Comment by EynsherKiel** [comment]
Thank you !!))

**Comment by andylippitt** [comment]
If you came here trying to understan unit.value, see: https://github.com/jbogard/MediatR/wiki#request-types
