### ISSUE TITLE
What is the reason to have non-generic request interfaces?

### ISSUE THREAD

**Issue by ggrnd0** [jbogard/MediatR#33]
Its make them similar for notification interfaces.
So, using of non-generic requests can confuse.

If you want response you must use requests, otherwise just notification.

**Comment by jbogard** [comment]
In the case of a request without a response, in case you don't have one. Notifications target multiple handlers, also.

**Comment by ggrnd0** [comment]
Why you want to know what notification will handle once?

**Comment by jbogard** [comment]
Not quite sure I understand you - both Send and Publish block for handlers to respond.

Sometimes Send doesn't have a response, but since C# doesn't let you use a Void type as a type parameter, I had to create a helper interface.

Send = 1 -> 1
Publish = 1 -> *

Send = Request/Response. Sometimes response is null
Publish = Broadcast. Can't have a response.
