### ISSUE TITLE
Question: Multiple request handlers

### ISSUE THREAD

**Issue by SharpNoiZy** [jbogard/MediatR#335]
I want to do something, but I don't know how to do it right with MediatR.

I want to have a Request "Search" with a parameter "Url" that returns a response "SearchResult".
That one I will call in a Web UI project.

I want to handle that request in a lib called "Scraping". (SearchHandler, No problem so far)
I have a lib called Scraping.Abstractions with a request "SearchByUrl" with a parameter "Url" that returns a response "SearchResult".

But now I have muliple libs referenced in Scraping, "Scraping.Google" and "Scraping.Bing" which reference "Scraping.Abstractions".
And have their handlers for "SearchByUrl".

What I have to do now, is to decide on runtime in SearchHandler with the url coming in, which Handler of SearchByUrl to call (To call just one, not two (In this easy example))

Can I achive this?

**Comment by FuncLun** [comment]
To me, it sounds like you're asking MediatR to do something your Dependency Injection framework should do. 

Assuming you have: 
`public class SearchRequest : IRequest<SearchResult>`
and handlers:
`public class GoogleScraper : IRequestHandler<SearchRequest, SearchResult>`
`public class BingScraper : IRequestHandler<SearchRequest, SearchResult>`

In your DI, register each of the scrapers as Keyed. Here's one way to do it with Autofac:
```
builder.RegisterType<GoogleScraper>()
    .Keyed<IRequestHandler<SearchRequest, SearchResult>>("www.google.com");
builder.RegisterType<BingScraper>()
    .Keyed<IRequestHandler<SearchRequest, SearchResult>>("www.bing.com");
```

This will register a `Func<SearchRequest, IRequestHandler<SearchRequest, SearchResult>>`:
```
builder.Register((c, p) =>
{
    var key = p.TypedAs<SearchRequest>().Host;
    return c.ResolveKeyed<IRequestHandler<SearchRequest, SearchResult>>(key);
}).AsImplementedInterfaces();
```

You would create this handler, and register it in your DI for MediatR to use:
```
public class Scraper : IRequestHandler<SearchRequest, SearchResult>
{
    public Scraper(Func<SearchRequest, IRequestHandler<SearchRequest, SearchResult>> scraperFactory)
    { ScraperFactory = scraperFactory; }

    private Func<SearchRequest, IRequestHandler<SearchRequest, SearchResult>> ScraperFactory { get; }

    public Task<SearchResult> Handle(SearchRequest request)
        => ScraperFactory(request).Handle(request);
}
```

Now, MediatR will get `Scraper`, which will forward to the correct Handler.
(Of course, I'm using a bad key, because what if the host is 'google.com' or 'www.Google.com', etc. Best to send request to a parse function to return an enum or a const string.)
