### ISSUE TITLE
How to Make Notification fire and forget

### ISSUE THREAD

**Issue by WangFeng2333** [jbogard/MediatR#349]
The code which publish the Notification will wait for the Notification handled ; but the Handler might be very slow, and this kind of Event is fired and forgot, we don't care about the result.

I knew I can use Task.Run( ()=> mediatR.Publish(...)) ; but do we have some native interface from MediatR

Thanks

**Comment by jbogard** [comment]
https://github.com/jbogard/MediatR/wiki#publish-strategies

**Comment by dosper7** [comment]
@jbogard I checked the version ParallelNoWait that does the fire and forget thing, but does this support the DI container? 

For instance, if in a NotificationHandler I have some injected scoped services aren't they disposed after the request ends and in this case II will need to use the singleton IServiceScopeFactory to acquire those dependencies and, in some way, do some anti-pattern by having to change the Notification class to get the ServiceScopeFactory alone and not be explicit about the NotificationHandler dependencies and make the unit tests harder?

**Comment by jstafford5380** [comment]
Yeah that did it. I just made the service scope a required service for CusomPublisher, then implemented IDisposable which disposes the scope with the service.

This configuration seems to work. I definitely feel like there's a better way to do this, but it seems to work.

``` csharp
services.AddScoped<ServiceFactory>(p => p.GetService);
services.AddScoped(p =>
{
    var scope = p.CreateScope();
    var provider = scope.ServiceProvider;
    return new CustomPublisher(provider.GetService<ServiceFactory>(), scope);
});
```

I think switching the publisher to scoped allows all children to be scoped as well so they're not captured. Creating another scope prevents it from getting disposed when the other handler (the one that calls the custom publisher in the first place) gets disposed, any shared dependencies (those created in the same scope) don't get disposed before the notification handlers get to use them. Then since the publisher is disposed at the end of the operation, the scope goes with it as well (due to disposing it within the publisher's dispose method). I probably could have achieved the same thing by making everything transient, but that screws with some of my session management (e.g. ravendb).
