### ISSUE TITLE
Pass over the handler instance to the middleware

### ISSUE THREAD

**Issue by stefansz-umusic** [jbogard/MediatR#351]
Sometimes you want the actual instance of the handler in the middleware (Pipeline behaviour), for example to read class attributes or check if it implements a particular interface 

Can the Mediatr be extended to pass the handler instance?

```
var handlerInstance = GetHandler<IRequestHandler<TRequest, TResponse>>(serviceFactory);
Task<TResponse> Handler() => handlerInstance.Handle((TRequest) request, cancellationToken);
            return serviceFactory
                .GetInstances<IPipelineBehavior<TRequest, TResponse>>()
                .Reverse()
                .Aggregate((RequestHandlerDelegate<TResponse>) Handler, (next, pipeline) => () => pipeline.Handle((TRequest)request, cancellationToken, next, handlerInstance))();
```

**Comment by jbogard** [comment]
No, but you can make your middleware take the handler as a dependency.

**Comment by stefansz-umusic** [comment]
Hi jbogard, 

Thanks for the reply.

Would the middleware get the same handler instance injected in the constructor as the one being executed in the next() call? I guess the IoC needs to be configured to create only one instance (singleton) per request context... for this to work. 

I want to add middleware that can set properties on the handler, for example the security context (property injection).  
```
public interface IWithUserContext  {
 User User {get; set;}
}

public class CommandHanlder : IWithUserContext {
    public User User {get; set;}

    Task Handle(Command command) {
    if(this.User.IsAdmin) { 
    }
   }
}
```

Passing the handler instance to the middleware via Handle method guarantees that the middleware gets same instance as the one executed via next().

**Comment by stefansz-umusic** [comment]
@lilasquared 

Thanks for the reply.

The request message should be a simple DTO object, that I expose to other systems as a nuget package and it shouldn't have any other dependencies (apart from mediatr library). Also, the message should be immutable.

Adding interfaces and attribute members around them seems wrong to me, as it creates dependencies to your domain and other infrastructure packages. The command handler should describe itself (required context, security requirements etc), and the middleware facilitates the command/query handler with all these crosscutting concerns.

**Comment by lilasquared** [comment]
Definitely valid points.

I agree that a command handler should describe itself, but also it's own dependencies.  In this case could the request simply have a userId, and then the handler could use some IUserService to request the User context using that Id?  

If the point is to avoid re-implementing the logic for getting the user context and the have that be part of the middleware's job, it seems a bit of misdirection.  If you are looking at the command handler class how do you know it is getting the user from somewhere else?

**Comment by stefansz-umusic** [comment]
@lilasquared 

I agree with you, but on that note all middleware creates misdirection if you are only looking at the command handler logic.  

The command handler describes itself by saying what it needs (i.e. implement INeedUserContext) and relies on the middleware/infrastructure to get that context. An alternative is to create base classes for your handlers, but can end up having too many.
By using middleware it allows you be more granular in the features that you want to enable for your handler .

Also, decorating your command handler serves multiple purposes (not only to provide context like loading an aggregate or the user context). Can also be used for things like:

[PerformanceMaxExecutionTime("100ms")]
[Security(Allow.OnlyAdminRoles)]
public class ExampleCommandHandler {
 //public void Handle(....) {}
}

**Comment by lilasquared** [comment]
@stefansz-umusic 

I wouldn't say all middleware creates misdirection.  For example logging all requests is something a middleware behavior can do and is not the command handlers responsibility, so there is no misdirection there.  You're right though that implementing the interface at least gives the reader some idea that there is a User context being provided by something.

If these requests are coming from a web interface and are scoped to nested containers per request, then injecting the handler into the middleware *should* give you the same instance since by default everything is container scoped.  

The reason I am a hesitant on that though is the handler itself no longer has a single responsibility.  In one case it is handling the request, but in another it is essentially being used as a cache for this user context to hold onto the data between middlewares / handler.  Maybe an argument could be made that since it needs the user context it is still the same responsibility. 

One solution I can think of would be to introduce a 3rd party to have the responsibility of caching / providing the context.  Inject UserContextProvider into both the middleware and the handler.  In the middleware set the context, and in the handler read the context.

**Comment by stefansz-umusic** [comment]
@lilasquared

The whole idea of having context marker Interfaces is to overcome the fact that I can't pass in the context via the handle method (ie add a RequestContext object).

**Comment by lilasquared** [comment]
Both the middleware and handlers can have the provider injected via the constructor.

**Comment by jbogard** [comment]
If you're trying to go the property injection route, setting state on your handlers themselves, I'd strongly caution you against that. At most, I'd set state on shared services, not on a handler itself.

**Comment by jbogard** [comment]
I've done both too for context information - information passed in on the request object itself and context-based services. They each have their benefits and drawbacks, but I think at this point something like `IUserContext` with a lazily-evaluated property has worked best. It's explicit to developers, but without having to rely on a pipeline step to set the value (whether in MediatR or something like an action filter).

**Comment by stefansz-umusic** [comment]
@jbogard 

> If you're trying to go the property injection route, setting state on your handlers themselves, I'd strongly caution you against that. At most, I'd set state on shared services, not on a handler itself.

Why storing the context/state on the handler itself is bad (via middleware)?  

I assume the handler is being disposed after every execution, so its not really acting as a cache/shared state service that can get the handler in an invalid state between calls. I believe Asp.net MVC works in a similar way, the middleware interacts with the context and then the context is being set by the controller activator onto the controller itself which later gets disposed as the request finishes.

**Comment by jbogard** [comment]
Mainly because it's easier to take a dependency on `IUserContext` or similar than it is to have essentially traits/mixins with interfaces and relying on generic constraints to get things wired up correctly. You'll have fewer headaches just supplying your handlers with dependencies than trying to have them wired up directly.
