### ISSUE TITLE
Are Decorators Supported?

### ISSUE THREAD

**Issue by mpaul31** [jbogard/MediatR#37]
are there any issues with using decorators for the request handlers for example using simple injector?

**Comment by jbogard** [comment]
I don't know, are there?

**Comment by jbogard** [comment]
I use decorators all the time with StructureMap using MediatR if that's what you're asking.

**Comment by mpaul31** [comment]
i have not had a chance to give it a spin but that makes me feel better knowing you use them all the time.

i have not decided upon a DI framework yet but was thinking StructureMap or SimpleInj. Wasn't looking forward to writing YetAnotherCommandHandler framework ;)

Thanks Jimmy

**Comment by bapti** [comment]
I use simple injector and have have used generic and specific decorators with MediatR without issue.  Really gets rid of those cross cutting concerns like logging, metrics timing, transactions etc.

**Comment by maldworth** [comment]
A little late to the party :), but I'm using mediatr with AutoFac and generic decorators as well. Working like a charm. You can see a [sample of it working here](https://github.com/maldworth/OnionWebApiStarterKit/blob/master/OnionWebApiStarterKit.Bootstrapper/App_Start/MediatorModule.cs)

**Comment by sstorie** [comment]
@maldworth Does this work with IAsyncNotification handlers as well? I'm trying to use this approach and can't get it working with notifications when I don't provide any decorators. If I include a decorator then my notifications handlers are called multiple times (twice in the case of adding a single decorator).

I've got a somewhat simpler implementation of your approach using this code:

```
        private static void RegisterHandlers(ContainerBuilder builder, Assembly[] assemblies, Type handlerType, params Type[] decorators)
        {
            builder.RegisterAssemblyTypes(assemblies)
                .As(t => t.GetInterfaces()
                          .Where(v => v.IsClosedTypeOf(handlerType))
                          .Select(v => new KeyedService(handlerType.Name, v)));

            for (int i = 0; i < decorators.Length; i++)
            {
                RegisterGenericDecorator(
                    builder,
                    decorators[i],
                    handlerType,
                    i == 0 ? handlerType : decorators[i - 1],
                    i != decorators.Length - 1);
            }
        }

        private static void RegisterGenericDecorator(
            ContainerBuilder builder,
            Type decoratorType,
            Type decoratedServiceType,
            Type fromKeyType,
            bool hasKey)
        {
            var result = builder.RegisterGenericDecorator(
               decoratorType,
               decoratedServiceType,
               fromKeyType.Name);

            if (hasKey)
            {
                result.Keyed(decoratorType.Name, decoratedServiceType);
            }
        }
```
Then the code calling this looks like this:
```
            RegisterHandlers(
                builder,
                assemblies,
                typeof(IAsyncRequestHandler<,>),
                typeof(AsyncValidatorHandler<,>),
                typeof(AsyncCommandPipeline<,>),
                typeof(AsyncAuthorizationHandler<,>));

            RegisterHandlers(
                builder,
                assemblies,
                typeof(IAsyncNotificationHandler<>));
```

However, in this case the notification handlers are never called. If I change that second statement to this instead:
```
            RegisterHandlers(
                builder,
                assemblies,
                typeof(IAsyncNotificationHandler<>),
                typeof(AsyncNotificationPipeline<>));

```
Then each notification handler is called twice, instead of a single time.

I think it's more of a problem with Autofac than anything to do with MediatR, but I started heading in the right direction based on the code you shared, so thank you for that :)

FWIW, I'm using Mediatr-2.0.0-beta-005 at the moment.

**Comment by maldworth** [comment]
@sstorie The first notification handler will not work, and I can quickly explain why. When you start registering decorators it takes advantage of the [Named/Keyed](http://docs.autofac.org/en/latest/advanced/keyed-services.html) autofac feature. But when using this feature, that means when resolving a named service, you have to pass in the name. But when wire up the Mediator resolver:
eg.
```csharp
// Sets the delegate resolver factories for Mediatr.
// These factories are used by Mediatr to find the appropriate Handlers
builder.Register<SingleInstanceFactory>(ctx =>
{
    var c = ctx.Resolve<IComponentContext>();
    return t => c.Resolve(t);
});
builder.Register<MultiInstanceFactory>(ctx =>
{
    var c = ctx.Resolve<IComponentContext>();
    return t => (IEnumerable<object>)c.Resolve(typeof(IEnumerable<>).MakeGenericType(t));
});
```

You'll notice that we don't resolve with passing in a name, which we don't want. So to get around this you'll notice that the helper method has this if statement:
```csharp
if (hasKey)
{
    result.Keyed(decoratorType.Name, decoratedServiceType);
}
```
Which means, *only key this decorator if it is __not__ the outer most decorator*.

You can see I was doing this in an ugly way [here](https://github.com/maldworth/OnionWebApiStarterKit/blob/0e883cdfc37c3d30f38647995453d65a6f1fb046/OnionWebApiStarterKit.Bootstrapper/App_Start/MediatorModule.cs), before I cleaned it up in a later commit. You'll notice that I commented the outermost decorator, and there is no `toKey:`.

Now, why your second one is getting two notification calls? I'm not sure, because I just tested it out using your static helper methods (instead of mine) to register a single notification handler. The notification handler was called once as expected when using the second register statement you provided. I also made sure I was using beta-005.

**Comment by sstorie** [comment]
@maldworth Thanks for the response. I started to better understand how the decorators in Autofac work as I continued to debug this yesterday, and it makes sense to me now why my first attempt failed. Your explanation helped confirm that I'm understanding this now.

I still don't understand why I get notification handlers called multiple times, but perhaps it's a problem with my decorator itself. I'm not sure though because the decorator is *also* called twice, so it's like the container is giving the mediator those multiple instances or something. I'll keep digging :)

Thanks again for responding to my question.
