### ISSUE TITLE
Best practice for using the current user (jwt)

### ISSUE THREAD

**Issue by zHaytam** [jbogard/MediatR#433]
Hello,

I'm considering using MediatR for the first time but I want to know what's the best way to access the current user (id)?

- Have a request with all the needed infos + userId and a model without the userid and map between them, this creates duplicate stuff.
- Have API users to always include the user id
- Create a service that gets the user from the context and use that in the handlers

Anyone has some real-world experience in this?  
Thank you!

**Comment by jbogard** [comment]
Are you in ASP.NET Core?

**Comment by zHaytam** [comment]
Yes, sorry I forgot to mention. I also use a clean architecture and would like to seperate then handlers/requests outside.

**Comment by jbogard** [comment]
I don’t know what that means. Are you hosting in ASP.NET Core?

**Comment by zHaytam** [comment]
Yes

**Comment by jbogard** [comment]
In that case, you can register and add a dependency for `HttpContext`:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-2.2#use-httpcontext-from-custom-components

That lets you get access to anything dealing with the current request.

We typically wrap that in some kind of service, `IUserContext` or similar, making it much easier to test with. `HttpContext` is....not easy to mock/fake.

**Comment by zHaytam** [comment]
Okay, that sounds good enough, especially in a service. Thanks!

**Comment by PureKrome** [comment]
@jbogard and @zHaytam - sorry to raise this closed issue ... but I have a question about this (and didn't want to create a new issue because most of the relevant info is in here).

> We typically wrap that in some kind of service, IUserContext or similar, making it much easier to test with. HttpContext is....not easy to mock/fake.

Okay - I'm not sure I fully understand this and I'm hoping for some help.

So to make sure I'm groking this, lets make sure I'm on the same page.

- A user 'authenticates' with the Web Api using a JWT. (yay! love JWT's)
- The "normal" ASP.NET Core controller pipeline converts/validates this JWT into a `ClaimsPrincipal`, etc. and sticks this instance into the `HttpContext.User` property.

So we're now auth'd against out API.

But it's bad practice to pass around the `HttpContext`. Especially since we only need the `User` property (in this scenario/GH-issue).

As such, what we should do is create an class which has a [Scoped DI lifetime](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#scoped) which exposes the User property.

NOTE: Notice i'm passing in an `HC-Accessor` as the docs suggest...

```
public class UserContext : IUserContext
{
    public UserContext(IHttpContextAccessor httpContextAccessor)
    {
        User = httpContext.User;
    }

    public User User { get; }
}


/// Wire this up in startup.cs
services.AddScoped<IUserContext, UserContext>();

```

and then this is injected into our handler....

```
public class Handler : IRequestHandler<Command, Response>
{
    public Handler(IUserContext userContext, ILogger<Handler> logger, etc)
    { ... }
}
```

Is this what you were talking about, @jbogard ?

**Comment by zHaytam** [comment]
That's what I personally did.

**Comment by PureKrome** [comment]
cheers!
