### ISSUE TITLE
MediatR 8 on nuget?

### ISSUE THREAD

**Issue by developermj** [jbogard/MediatR#439]
I wasn't sure where else to post this. What is the timeframe of getting the latest release deployed to nuget? I see in AppVeyor that 8.0 is built. Is there any assistance needed in getting the next release out the door?

**Comment by jbogard** [comment]
Every time someone asks I push the release out another month.

**Comment by developermj** [comment]
This seems like an inappropriate response to a simple question regarding a release for a project downloaded well over a couple million times on nuget. I'm offering any assistance you may need here. Are you able to provide any sort of timeframe for the next release?

**Comment by jbogard** [comment]
Every build is on myget. If you want the latest, find it there.

I don't like releasing major versions too close to each other. I want public API changes to stabilize before a release. More than 2 major releases a year with breaking API changes is too much for me to deal with on my own clients, who are really 99% what I care about since they actually pay the bills.

Pushing a release is simple, I've made sure of that. Dealing with API changes is not for consumers. I want to stabilize changes before release.

If this is not soon enough, I do have a 100% money-back guarantee.

**Comment by developermj** [comment]
Thank you for your response. Also thank you for your work on maintaining and running this project. It has been a great way to solve some of my code logic problems. One last question: Do you have a document anywhere on how to connect to your specific myget site?

**Comment by huysentruitw** [comment]
The feeds are listed here https://myget.org/users/jbogard
