### ISSUE TITLE
Communication between modules - MediatR or Interface/Facade?

### ISSUE THREAD

**Issue by dario-l** [jbogard/MediatR#440]
I'm involved in fully modular monolithic application project. We use MediatR like Jimmy describes in this article: [Dealing with Duplication in MediatR Handlers](https://lostechies.com/jimmybogard/2016/12/12/dealing-with-duplication-in-mediatr-handlers/). Exactly this:

>  I want MediatR to serve as the outermost window into the actual domain-specific behavior in my application

But what with internal communication?

We have some doubts about communication between modules. We use Events and Queries (in monolithic application it is sometimes useful and inevitable). Especially we have problem with queries. If one module must query another then our handlers use `IMediator` (again) for executing queries from other modules. It looks odd and breaks our approach. 

Jimmy mentions `Excluding sub-handlers or delegating handlers, where should my logic go?` but we do not know what that handlers are.

Maybe we should just use simple interfaces (aka public facade) for this?
It will be cleaner and everything will be clearly defined.

**Comment by djjlewis** [comment]
I'm not associated with the MediatR project anyway (although I do use it), but it feels this question would be best suited to Stack Overflow rather than here as it's not directly related to a project or code issue?

Just as a quick response, we use a combination of techniques for code reuse once passed the initial MediatR handler such as (domain) service classes. I don't treat queries any differently usually, i.e. wrap the query up in a class / interface and then inject as a dependency for both handlers. Commonly I'll just have an `Execute()` method on a simple query class that takes some params and returns the correct list type.

For events, we have a nice domain events system where they get persisted to the DB in the same transaction then an out of process manager that uses MediatR notifications / handlers to process these.

If you do end up posting something to SO, let me know and I can go into more detail.

**Comment by dario-l** [comment]
Thanks for reply. I posted on SO the same question here: https://stackoverflow.com/questions/58060860/communication-between-modules-mediatr-or-interface-fasade :)
