### ISSUE TITLE
Problem using Unity where dependency has Scoped lifetime.

### ISSUE THREAD

**Issue by webm0nk3y** [jbogard/MediatR#454]
We are experiencing an issue using Mediatr + Unity. 

We discovered that a dependency registered with Unity with a HierarchicalLifetimeManager in our web application is being reused when it is injected into a Notification & Request Handlers which are transient.

**Comment by OBezhan** [comment]
Hello,

I'm wanted to create a new issue but  I saw this one ;)

We have run into the same problem. We have an ASP .Net MVC 5 application that uses Unity as DI container. We have a DbContext class registered with HierarchicalLifetimeManager ( scoped, per request),
Repository - registered as transient. For IMediator and IRequestHandler registration, we have used the code from the [example](https://github.com/jbogard/MediatR/blob/master/samples/MediatR.Examples.Unity/Program.cs) ( IMediator registered with HierarchicalLifetimeManager, all handlers registered as transient and ServiceFactory registered as an instance)
<details>
  <summary>Some detailed examples</summary>


    public class DbContext {  }
    public class GenericRepository
    {
        private readonly DbContext _dbContext;

        public GenericRepository(DbContext dbContext)
        {
            _dbContext = dbContext;
        }
    }

```
public class Handler : IRequestHandler<Query, IDictionary<int, string>> {
	private readonly GenericRepository _repository;

	public Handler(GenericRepository repository) {
		_repository = repository;
	}
}
```
```
container.RegisterType<IMediator, Mediator>(lifetimeManager)
     .RegisterInstance<ServiceFactory>(type =>
     {
        var enumerableType = type
             .GetInterfaces()
             .Concat(new[] { type })
             .FirstOrDefault(t => t.IsGenericType && t.GetGenericTypeDefinition() == typeof(IEnumerable<>));

      return enumerableType != null
                ? container.ResolveAll(enumerableType.GetGenericArguments()[0])
                : container.IsRegistered(type)
                     ? container.Resolve(type)
                      : null;
       });
```

</details>

I have found the root cause of this issue - ServiceFactory registration. 
Let me explain. When you registering ServiceFactory as an instance (== singleton) you capture the instance of IUnityContainer container to the closure, so the same instance of the container will be used on every resolve. Unity implements scoped lifetime by creating child containers for each scope ( request, for example). So, normally for every request will be used new child container, and a new instance of DbContext will be created. But with this closure, we will always use the same instance of the container (a one that was created for the first request) and this causes unexpected behavior. 

I have fixed it by rewriting ServiceFactory registration.
Instead of code below (simplified example from the documentation)

`
container.RegisterInstance<ServiceFactory>(type =>
container.Resolve(type));
`

it's better to use [InjectionFactory](http://unitycontainer.org/api/Unity.Injection.InjectionFactory.html) class. For example,

```
container.RegisterType<ServiceFactory>(new HierarchicalLifetimeManager(), new InjectionFactory(
	childContainer=> (ServiceFactory) (type => childContainer.Resolve(type))
));
```

In this case, we also capture childContainer instance in the closure, but a child container ( that will be created for every request ) instead of a parent container. So, DbContext will be resolved once per request, as expected.

@jbogard If you think that it's a good solution, I could create a pull request to change the example with Unity usage.

P.S. About the drawbacks.
The main problem with this solution is that we'll create an instance of ServiceFactory for every request. I think it's not a big deal if we'll cache the result of reflection :

```
Type enumerableType = type
	.GetInterfaces()
	.Concat(new[] {type})
	.FirstOrDefault(t =>
		t.IsGenericType && t.GetGenericTypeDefinition() == typeof(IEnumerable<>));
```

For example, we could use static ConcurentDictionary<Type, Type?> where the key is input type and the value is the result of `enumerableType.GetGenericArguments()[0]` evaluation if the type is IEnumerable and null otherwise.
