### ISSUE TITLE
Is Possible Call a Dispose or Destructor method in MediatR Pipeline?

### ISSUE THREAD

**Issue by Praticis** [jbogard/MediatR#513]
I have a MediatR pipeline called ErrorCatchPipeline. It involves all request handlers inside of transparently try catch, to automatic prevent and registrate untreated errors.

When an exception occurs, I want that my pipeline call destructor or Dispose method of request handler (All my request handlers implements IDisposable interface). 

It is possible?

In MediatR pipeline, the request handler is a wrapper implementation and not provide concrete handler type

**My handler**
![image](https://user-images.githubusercontent.com/56609579/80760850-f63a2f00-8b0f-11ea-82e2-b63b3b2f3a3c.png)

**My Error Catch Pipeline**
![image](https://user-images.githubusercontent.com/56609579/80761080-4618f600-8b10-11ea-949e-6ba93c3719a4.png)

**Comment by lilasquared** [comment]
Typically MediatR is used in conjunction with a Dependency Injection library which should own the lifecycle of your handlers and services.  Manually disposing your handlers or subsequent repositories doesn't seem like an appropriate design pattern.  I would suspect that it is not possible do to what you are asking because the pipeline and handler classes are not coupled in any way nor do they know about each other.  

Your services and handlers can be declared on the DI Container to be Transient or Scoped which will ensure they are disposed appropriately after a request or transaction completes.
