### ISSUE TITLE
Separate the response from the request

### ISSUE THREAD

**Issue by figueiredorui** [jbogard/MediatR#524]
I have been using MediatR and I have a question at the back of my mind for a while.

What is the reason for a IRequest needing to know about the response type IRequest<T>
It seems to me that the request could know nothing about the response and would be up to the handler to match requests with responses.

I was thinking that something like this could work?

```
public class MyRequest: IRequest{}
public class MyResponse: IResponse{}

public class MyHandler : IRequestHandler<MyRequest, MyResponse>{

public MyResponse Handle(MyRequest request, CancellationToken cancellationToken)
{
}

}

_mediator.Send<MyResponse>(new MyRequest());
```
I hope it makes sense.
Cheers.

**Comment by jbogard** [comment]
Because in my usage, I'm not trying to decouple the request for the response. Requests and responses are logically tied together for me. Otherwise the caller has to "guess" on the response, and you have implicit coupling, instead of explicit.

In the messaging world, requests and responses are intentionally coupled, and the component that defines the request also defines the response.

**Comment by figueiredorui** [comment]
Hi @jbogard, seems a valid reason to me to couple the response with the request.

**Comment by phlashdev** [comment]
@figueiredorui so it seems that the answer from @jbogard has cleared things up for you. So I think we can close this issue now, or do you have another question related to this?
