### ISSUE TITLE
PublishStrategy sample and multiple notifications

### ISSUE THREAD

**Issue by belius** [jbogard/MediatR#548]
I am checking the sample for PublishStrategy, for a procedure I am creating that shoul publish 5 parallel notifications in a Fire and Forget way.

BTW, even if I can pass to the public `Publish `method the `PublishStrategy.ParallelNoWait`, it looks like I can only pass one notification a time.....while the private method `Task ParallelNoWait(....)` seems to work with an Array.

Do I miss something or the **Publisher.cs** is missing the `Publish `method with an `Enumerable `of notifications?

**Comment by jbogard** [comment]
The array is for the *handlers*, you can still only call `Publish` one at at time. If you want to publish 5 different notifications in parallel, you can compose that when you call `Publish` into multiple tasks and handle the parallelization on the calling side. I don't plan to support accepting multiple notifications, since you can just call the method multiple times.
