### ISSUE TITLE
Are there any performance concerns wiring up too many decorators?

### ISSUE THREAD

**Issue by ThisNoName** [jbogard/MediatR#55]
I have the typical crosscutting stuff like validation, authorization, auditing, transaction and error logging as decorators.  They check attributes on the requests and do their part.  Since most of them are done via other frameworks, there's not much code in them.  Right now, each is a separate decorator and wired up using SimpleInjector.  It sounds like following SRP this way.  

But is it really necessary?  Are their any performance penalty having too many decorators?  Since none of the steps are optional, is it better if I leave them all in one place?  Decorator performance aside, I assume it would at least shave off a few nanoseconds reflecting attributes?

Appreciate your thought.

**Comment by jbogard** [comment]
Have you measured the performance with/without the decorators?

**Comment by whoever123** [comment]
Don't think I know enough to write that kind of test and analysis.  Took me quite a while just to get things up and running.  It's a really amazing framework and having huge impact on application architecture.  Now my controllers are so skinny I wonder why they are even there!

I reread your post about crosscutting concerns, seems one of the benefit of separate decorators is the flexibility during unit test.  Though I'm not too good at that either ^_^

While playing around, I came up with this using SimpleInjector

    container.RegisterDecorator(typeof(IRequestHandler<,>), typeof(TransactionRequestHandler<,>),
       c => c.ImplementationType.GetInterfaces().Where(i => i.IsGenericType 
                    && i.GetGenericTypeDefinition() == typeof(IRequestHandler<,>))
            .SelectMany(i => i.GetGenericArguments()).First()
            .UnderlyingSystemType.Attributes(typeof(TransactionAttribute)).Any());

It basically takes the handler, find the request and decorate if there's a TransactionAttribute on the request.  Same can be done to all other decorators except validation.

My understanding is that registration only runs during application start up, so it won't have too much impact with added code.  And this would allow separate decorators while avoiding unnecessary decoration and attribute reflection at run time.

Let me know if you see any issue with this approach.  Or if there's a lesser crazy looking way.  

Thanks

**Comment by jbogard** [comment]
Hmmm that's interesting, I've not thought about using attributes to conditionally decorate handlers. Are there handlers that wouldn't be transactional?

**Comment by whoever123** [comment]
We do a lot of auditing.  I assume between viewing a message and auditing, there's some performance benefit if you don't start a transaction?  Again, never tested, I just assumed it.  

Before, I had AuditRead and AuditWrite attribute decorating requests that need to be audited.  So the audit decorator ("interceptor" in my previous Agatha RRSL implementation) also doubles as transaction decorator.  Along the same thought, if validation, authorization (seems always needed) are always attached through their own respective decorators , why not wrap them altogether and you only need to read those attributes once.  That lead to my original question.

Now that with conditional decorator, for the optional auditing and transaction (maybe caching as well?), it seems making perfect sense to have separate decorators and mix and match as needed.  

For validation, I moved MediatR Requests into a separate project and shared them in WebApi as Models.  This would allow FluentValidation take care of validation before reaching service layer.    The only thing I'm still struggling are actions with primitive parameters because you can't attach IValidator to them.  So I still need to wire up validation decorator in service layer and end up validating everything twice.

I'm not sure which way is better.  Insist on complex model parameter only?  Or pass everything directly to service and let it throw exception?  Or validating twice but with less chance of exception.  I do map exceptions into model state in WebApi, so the end result is the same, just what happens under the hood, if they matter at all.

Sorry for the long rambling.  Learning great stuff isn't easy for some of us ^_^

**Comment by jbogard** [comment]
So for the two models thing - there's not a hard and fast rule here. If you're moving validation into MediatR, then you can easily get away with using a primitive in the controller action parameter and creating a request from there. If you're integrating directly with MVC validation, then I'd opt for requests as controller parameters. I would try not to double-validate as much as possible.
