### ISSUE TITLE
NullReferenceException in MediatR.Mediator.Send using StructureMap in a test harness

### ISSUE THREAD

**Issue by adhalejr-awh** [jbogard/MediatR#569]
[MediatrWithSpecsFor.zip](https://github.com/jbogard/MediatR/files/5394171/MediatrWithSpecsFor.zip)

It's happening with 8.1.0 and 9.0.0. I've reproduced the problem with a pretty small class library - 1 request and 1 handler - and a simple test harness - SpecsFor which uses StructureMap (see attached zip file). I'm following the steps at https://github.com/jbogard/MediatR/wiki to set up the container. If I debug the test and examine the container, I see all the expected types in it. The Mediator object is there. The Send method is called. But it never reaches the Handle method of the handler b/c it gets a NullReferenceException. This is the stack trace:

```
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ReverseIterator`1.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at MediatR.Internal.RequestHandlerWrapperImpl`2.Handle(IRequest`1 request, CancellationToken cancellationToken, ServiceFactory serviceFactory)
   at MediatR.Mediator.Send[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at MediatrApp.BaseRequest`1.<HandleAsync>d__2.MoveNext() in D:\Src\TestFrameworkResearch\MediatrWithSpecsFor\MediatrApp\BaseRequest.cs:line 17
```

I realize this isn't necessarily the normal scenario for MediatR. But since it's documented as working with StructureMap, and since if it's used in a StructureMap-based application it should be able to be tested in a StructureMap-based test harness (IMO), then what I've put together should work. I've pulled in the MediatR code while debugging, but there's too much going on in a single line within the Send method and within the RequestHandlerWrapperImple.Handle method for me to figure it out.

Thank you.

**Comment by lilasquared** [comment]
Thanks for the repro repo, but in the future its easier to just add it as a repo to your profile on github.  I'm assuming you're injecting the IMediator into the request just to show a particular failure?  There would never be any scenario where this would be valid in a real world application.  I could be misunderstanding what you are trying to show.

**Comment by lilasquared** [comment]
After messing around with this for a bit I would guess the issue is in the SpecsFor library, not in MediatR.  Whatever engine SpecsFor is using to build the structuremap container in conjunction with Moq might be messing it up.  Given that repo hasn't seen activity in a while it might be an issue that you need to fix yourself.

**Comment by lilasquared** [comment]
In a normal scenario with structure map or any other container library, when you ask for a collection of instances, the container will give you an empty collection if there are none. Which is the case here. If you want to add behaviors you can register them (see the samples folder) and then the collection would be non-empty. In either case with the auto mocker that is being used by SpecsFor, you will get back a mocked IEnumerable which won’t work. This is because the StructureMap Automocker adds functionality to the container that ensures a mock is returned for anything that doesn’t explicitly have a registration.  It’s possible to work around this by adding your own policy to the container which would be applied before the automocking policy if you want to continue using this testing library.

**Comment by adhalejr-awh** [comment]
At the risk of becoming annoying (or maybe more annoying than I already am)... In an earlier message you said: In this case mediator asks the service factory for a collection of PipelineBehaviors that can handle the request being sent.

I took that to mean that a PipelineBehavior somehow wraps an actual request handler type - "SimpleHandler" in my sample project. But maybe I misunderstood what you meant regarding PipelineBehaviors. What you say in your most recent message implies that these behaviors are optional ("if you want to add [them] you can register them").

So perhaps you can clarify that. More significantly, though, should I understand that if there is at least 1 real PipelineBehavior registered then StructureMap won't return an automock and MediatR might get a valid collection and be able to get past this exception? (FYI - I am going to look at the samples folder).

Thank you again.

**Comment by lilasquared** [comment]
Yes the Pipeline Behaviors wrap a request handler and act as middleware, passing the request through all matching behaviors.  They are optional, but the mediator always asks the service factory for them.  In normal execution if you have not registered any you will simply get back an empty collection.

If you register some in your test project you will still get back a mocked `IEnumerable<T>` this is because there is no explicit registration for the `IEnumerable<T>`.  The automocker overrides the default container behavior which would be to return all possible registered instances of `T` when being asked for `IEnumerable<T>`.   So even registering the behaviors will not work around this.  In order to get this to work you will need to add a custom IFamilyPolicy to the container.

**Comment by adhalejr-awh** [comment]
Thank you again, @lilasquared. Closing.

**Comment by lilasquared** [comment]
No problem.  I took a look at the default policies that StructureMap ships with, so if you want to work around the error easily you can register the default pipeline behaviors that come with MediatR (as seen in the samples) and then add this line to your container config.

```csharp
cfg.Policies.OnEmptyFamily(new EnumerableFamilyPolicy());
```

This way the enumerable policy will be applied before the AutoMocking policy.

**Comment by adhalejr-awh** [comment]
I think OnEmptyFamily in your sample code should be OnMissingFamily. Anyway... what you suggested gets around the null reference exception - in fact I don't even need to add the default pipeline behaviors, just the EnumerableFamilyPolicy.

Unfortunately, SimpleHandler never gets invoked. After the line _result = SUT.HandleAsync().Result; executes, _result is false. But SimpleHandler has never been instantiated or its Handle method invoked.

We're likely getting into the real esoteric stuff now.

**Comment by lilasquared** [comment]
Its not as esoteric as you think.  What's happening now is that the Automocker is giving you a mock pipeline behavior.  I thought that by adding the default ones it would prevent this but it does not.  Using the below policy will resolve the issue however you will no longer be able to test the pipeline behavior.  It will be more complicated to be able to test them since they rely heavily on closing generics which might be difficult to circumvent given the Automocking behavior.  The below policy simply forces the container to return an empty list.

```csharp
public class EmptyPipelineFamilyPolicy : IFamilyPolicy
{
    public PluginFamily Build(Type type)
    {
        if (EnumerableInstance.IsEnumerable(type))
        {
            var elementType = EnumerableInstance.DetermineElementType(type);

            if (elementType.Name == typeof(IPipelineBehavior<,>).Name)
            {
                var family = new PluginFamily(type);
                family.SetDefault(buildInstanceForType(elementType));

                return family;
            }

            return null;
        }

        return null;
    }

    public Boolean AppliesToHasFamilyChecks
    {
        get
        {
            return false;
        }

    }
    private static Instance buildInstanceForType(Type type)
    {
        var instanceType = typeof(List<>).MakeGenericType(type);
        var instance = Activator.CreateInstance(instanceType);
        return new ObjectInstance(instance);
    }
}
```

**Comment by adhalejr-awh** [comment]
That did it. I didn't need any of this kind of code from "samples":

cfg.For(typeof(IPipelineBehavior<,>)).Add ...

For the actual MediatR application I'm writing and testing, we're not using the pipeline behaviors; and I don't foresee us needing them. The main issue is relying solely upon StructureMap for DI when running under the test harness (whereas the application itself uses .net core's DI).

Thank you.

**Comment by lilasquared** [comment]
Great.  You may want to eventually look into alternate forms of integration testing that uses the same DI for both the tests and the application since they have different features.

**Comment by adhalejr-awh** [comment]
Agreed. I need to be able to specify response results for method calls on automocked objects. I can only do that if StructureMap generated the automocks. But I'd much prefer that everything related to MediatR use .net core's DI as the actual app does.
