### ISSUE TITLE
Question about using Mediatr in a modular monolith

### ISSUE THREAD

**Issue by fcastellsflip** [jbogard/MediatR#601]
In a microservice architecture, every microservice has its own Mediatr with its own behaviours pipeline. In a modular monolith, every module needs its own pipeline, but in this case, the Mediatr is shared (so that Notifications published from one module can be handled by other modules, for example). 
I believe that eventually, I'll find a similar need for having a different pipeline for Commands and Queries within a single module.

Is there a documented or recommented way of supporting this scenario? Are there any samples?

In case I have to build my own solution for this, I assume that it starts by being able to distinguish the requests from different modules with some custom interfaces.

**Comment by AlmarAubel** [comment]
Have a look at this project https://github.com/kgrzybek/modular-monolith-with-ddd. As far as I can see Kamil  each module has it own *startup class. This class will wire up the [mediator](https://github.com/kgrzybek/modular-monolith-with-ddd/blob/a97f3d5573153d16d107ade67bf2107ff8cc48a7/src/Modules/Meetings/Infrastructure/Configuration/Mediation/MediatorModule.cs) for each module. Instead of using the iPipeline behavior he is using a decorator pattern(see [ProcessingModule](https://github.com/kgrzybek/modular-monolith-with-ddd/blob/a97f3d5573153d16d107ade67bf2107ff8cc48a7/src/Modules/Administration/Infrastructure/Configuration/Processing/ProcessingModule.cs) in combination with Autofac.
