### ISSUE TITLE
Returning Result<T> from a behaviour.

### ISSUE THREAD

**Issue by TraceLD** [jbogard/MediatR#626]
MediatR version: 9.0.0
.NET target framework: `net5.0`
dotnet version: 5.0.201

I'm trying to implement FluentValidation without throwing an exception, and to do that I'm using a Result<T> type. I have the following Query:
```cs
public class TestQuery
{
    public record Query(string? TestString) : IRequest<Result<string>>;

    public class QueryValidator : AbstractValidator<Query>
    {
        public QueryValidator()
        {
            RuleFor(x => x.TestString)
                .NotEmpty();
        }
    }
    
    public class Handler : RequestHandler<Query, Result<string>>
    {
        protected override Result<string> Handle(Query request)
        {
            return request.TestString!;
        }
    }
```

and the behaviour written like so:
```cs
public class ValidationBehaviour<TRequest, TResponse> : IPipelineBehavior<TRequest, Result<TResponse>>
    where TRequest : IRequest<Result<TResponse>>
{
    private readonly IEnumerable<IValidator<TRequest>> _validators;

    public ValidationBehaviour(IEnumerable<IValidator<TRequest>> validators)
    {
        _validators = validators;
    }

    public Task<Result<TResponse>> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<Result<TResponse>> next)
    {
        var context = new ValidationContext<TRequest>(request);
        var failures = _validators
            .Select(x => x.Validate(context))
            .SelectMany(x => x.Errors)
            .Where(x => x is not null)
            .ToList();

        if (failures.Any())
        {
            return Task.FromResult(Result<TResponse>.FromError(new GenericError("test")));
        }

        return next();
    }
}
```
and I register the behaviour with DI like so:
```cs
services.AddTransient(typeof(IPipelineBehavior<,>), typeof(ValidationBehaviour<,>));
```

However the behaviour never runs when I run the query (I have verified with the debugger). What gives?

**Comment by lilasquared** [comment]
can you see if https://github.com/jbogard/MediatR/issues/510 leads you in the right direction at all?

**Comment by TraceLD** [comment]
> can you see if #510 leads you in the right direction at all?

I was hoping there was a way to do it without using `Activator` + a non-constrained `TResponse`.

**Comment by lilasquared** [comment]
I remember a comment in another issue about partially closed generics like this. (or maybe partially constrained?) but can't recall which it was or how it was related.  Does it work if you register the behavior as
```csharp
services.AddTransient(typeof(IPipelineBehavior<,>), typeof(ValidationBehaviour<Query, IRequest<Result<String>>>));
```

**Comment by takato1314** [comment]
Hi @TraceLD , I am currently trying to do something similar to your approach where I will do validations within the IRequestHandler and then I would want to return the errors without throwing exceptions. I just wanted to know if the `Result<T>` object that you're using is an implementation of  what described [here](https://github.com/jbogard/MediatR/issues/260#issuecomment-386952280) or issit something native from the FluentValidation library?

**Comment by TraceLD** [comment]
> Hi @TraceLD , I am currently trying to do something similar to your approach where I will do validations within the IRequestHandler and then I would want to return the errors without throwing exceptions. I just wanted to know if the `Result<T>` object that you're using is an implementation of what described [here](https://github.com/jbogard/MediatR/issues/260#issuecomment-386952280) or issit something native from the FluentValidation library?

In my case it comes from: https://www.nuget.org/packages/Remora.Results/ as I use https://www.nuget.org/packages/Remora.Discord/ for that project and it uses it extensively so I decided to adhere to that style in my own code too.

**Comment by kevbry** [comment]
I think the issue is right here:
https://github.com/jbogard/MediatR/blob/50af3de7fa89d56067952581179fa22a1b66de0b/src/MediatR/Wrappers/RequestHandlerWrapper.cs#L63

When mediatr is trying to locate your behaviours, it's asking whichever DI adapter you're using for the set of IPipelineBehavior<TRequest,TResponse> implementations it has registered. In this case, in RequestHandlerWrapperImpl, TRequest will be of type Query and TResponse will be of type Result<string>. This is an issue, because when RequestHandlerWrapperImpl asks DI for an IBehavior, it's going to try to instantiate ValidationBehaviour using the generic parameters <Query,Result<string>> and not the <Query,string> you were probably expecting it to ask for. If you turn on a first chance exception handler or look in the visual studio exception timeline you'll see an exception that looks like this (I changed the names of TRequest and TResponse in your behavior to TReq and TResp to differentiate them from the names in RequestHandlerWrapperImpl):

> 	Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll ("GenericArguments[0], TestQuery+Query', on 'ValidationBehaviour2[TReq,TResp]' violates the constraint of type 'TReq'.") Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll ("GenericArguments[0], 'TestQuery+Query', on 'ValidationBehaviour`2[TReq,TResp]' violates the constraint of type 'TReq'.")

I'm guessing your behavior registration looked like this (assuming you're using the microsoft DI container):
`services.AddTransient(typeof(IPipelineBehavior<,>),typeof(ValidationBehaviour<,>));`

If you change it to the following, you'll probably see it start working:
`services.AddTransient(typeof(IPipelineBehavior<Query,Result<string>>), typeof(ValidationBehaviour<Query,string>));`

If you want to not have to manually register every possible Result<T> => ValidationBehavior<?,T> combination, I think you're going to have to resort to reflection (what I did), or find a container that does the work of creating those closed implementation types for you. If there's another way to do it, I'd love to hear it. I'm fairly sure I remember seeing a bug in here a couple of years back that had some gnarly reflection code to accomplish this - I'll update if I can find it.

**Comment by TraceLD** [comment]
I've gone with reflection, like so:
```cs
public class ValidationBehaviour<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
    where TRequest : IRequest<TResponse>
    where TResponse : IResult
{
    private readonly IEnumerable<IValidator<TRequest>> _validators;

    public ValidationBehaviour(IEnumerable<IValidator<TRequest>> validators)
    {
        _validators = validators;
    }

    public Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
    {
        var responseType = typeof(TResponse);
        var context = new ValidationContext<TRequest>(request);
        var failures = _validators
            .Select(x => x.Validate(context))
            .SelectMany(x => x.Errors)
            .Where(x => x is not null)
            .ToList();

        // ReSharper disable InvertIf
        if (failures.Any())
        {
            var error = new ValidationError(
                $"Error while validating '{typeof(TRequest).ToFriendlyDisplayString()}'.", failures);
            var errorResult = responseType
                .GetMethod("FromError", new[] {Type.MakeGenericMethodParameter(0), typeof(IResult)})?
                .MakeGenericMethod(typeof(ValidationError))
                .Invoke(request, new object?[] {error, null});
            return Task.FromResult((TResponse) errorResult!);
        }
    
        return next();
    }
}
```
So far it has been working flawlessly, I'll update if I encounter any bugs.

**Comment by rahuldass** [comment]
@TraceLD can you please share what's inside your IResult interface?

**Comment by TraceLD** [comment]
> 
> 
> @TraceLD can you please share what's inside your IResult interface?

I use https://github.com/Nihlus/Remora.Results/blob/master/Remora.Results/IResult.cs

NuGet: https://www.nuget.org/packages/Remora.Results/

**Comment by rahuldass** [comment]
@TraceLD Thanks :)

**Comment by defunky** [comment]
Is there no way around this aside from reflection? How do people normally handle validation errors without throwing exceptions?

**Comment by Maggus503** [comment]
@TraceLD Could you share your DI code? I tried to use your solution with CSharpFunctionalExtensions Result types (https://github.com/vkhorikov/CSharpFunctionalExtensions/tree/master/CSharpFunctionalExtensions/Result), but couldn't make it work. The program never hits the handler. 

Would it be possible to use it if TResponse : IResult<T,Error>?
