### ISSUE TITLE
Async Notifications dbContext disposed

### ISSUE THREAD

**Issue by ZeSzymi** [jbogard/MediatR#675]
Hi

I have problem with DbContext in async Notifications. This is my code for running async notifications:

```
    public class ParallelNoWaitPublishMediator : Mediator
    {
        private Func<IEnumerable<Func<INotification, CancellationToken, Task>>, INotification, CancellationToken, Task> _publish;

        public ParallelNoWaitPublishMediator(ServiceFactory serviceFactory) : base(serviceFactory)
        {
            _publish = ParallelNoWait;
        }

        protected override Task PublishCore(IEnumerable<Func<INotification, CancellationToken, Task>> allHandlers, INotification notification, CancellationToken cancellationToken)
        {
            return _publish(allHandlers, notification, cancellationToken);
        }

        private Task ParallelNoWait(IEnumerable<Func<INotification, CancellationToken, Task>> handlers, INotification notification, CancellationToken cancellationToken)
        {
            foreach (var handler in handlers)
            {
                Task.Run(() => handler(notification, cancellationToken), cancellationToken);
            }

            return Task.CompletedTask;
        }
    }
```

And everytime i use DbContext in notification it gets disposed. The solution is to use service provider which creates new instance of dbContext when i call it, but I wanted something more generic. Is there any way to provide new scope for the handler, run in Task.Run() ?

**Comment by denisenko93** [comment]
This is because the DbContext is registered with DI as a Scoped Service by default and asp creates and closes the scope on every request. There are several ways to fix this behavior:

- Register all services used in notification handlers as transient or singletone
- Override ServiceFactory, create custom scope and close it after complete all handlers
- Use [IHostedService](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostedservice) for executing you async notifications
- Use external libraries like [Quartz.NET](https://www.nuget.org/packages?q=owner%3AQuartz.NET) or [Hangfire](https://www.nuget.org/packages/Hangfire) for executing you async notifications

**Comment by jbogard** [comment]
For option 2 there, here's some docs from MS on the subject:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&tabs=visual-studio#consuming-a-scoped-service-in-a-background-task
