### ISSUE TITLE
[Q] How to rollback executed command if next command failed?

### ISSUE THREAD

**Issue by dehghani-mehdi** [jbogard/MediatR#706]
Imagine I have 3 following commands which will be run in sequence:
- `InsertXCommand`
- `InsertYCommand`
- `InsertZCommand`

What is the best way to manage rollback in case of failure command?

**Comment by dehghani-mehdi** [comment]
I'm not sure if I got you correctly, so let me explain more.

Database tables:
`Products`: columns: `Id, Title`
`ProductCategories`: columns: `ProductId, CategoryId`

`InsertProductCommand`: this command insert given product into database and returns inserted product id
`InsertProductCategoryCommand`: this command insert new record into `ProductCategories` table based on given product and category, product will be inserted one from `InsertProudctCommand`.

By first approach you mean one command, e.g: `InsertProductCommand`, for inserting product and product category? If so, that doesn't violate Single responsibility principle?

**Comment by jbogard** [comment]
Yes, I'd combine all three things. It doesn't violate the single responsibility principle mainly because that principle is impossible to falsify. Is setting a single value a single responsibility? Or is performing a single action for a user a single responsibility?

Better to put a single user action in a single request handler, and THEN only refactor to smaller responsibilities as needed.

But the composition level granularity should not be command handlers. Instead you can compose other classes from that handler. I wouldn't do that prematurely though.
