### ISSUE TITLE
calling multiple send in same context throws error

### ISSUE THREAD

**Issue by Audhut** [jbogard/MediatR#715]
Hi  All,

I have a Quartz job which has to calls in the execute method

    public async Task Execute(IJobExecutionContext context)
    {
	              var pcs = await GetpcProcessing();

              pcs.ForEach(async pc =>
                      {
		              var eval1 = await  _mediator.Send(new RunEvaluationCommand(pc.id1, start, end));
		              var eval2 = await _mediator.Send(new RunEvaluationCommand(pc.id2 ,start, end))	 
              });

    }
		
when the second mediator is called it gives a  "**Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it (or one of its parent scopes) has already been disposed.**" i get the erro on the second call for (eval2 )
I am using autofac to register the mediator

       // Mediator itself
        builder
            .RegisterType<Mediator>()
            .As<IMediator>()
            .InstancePerLifetimeScope();

        // request & notification handlers
        builder.Register<ServiceFactory>(context =>
        {
            var c = context.Resolve<IComponentContext>();
            return t => c.Resolve(t);
        });

        builder
            .RegisterAssemblyTypes(typeof(RunEvaluationCommand).Assembly)
            .Where(t => t.IsClosedTypeOf(typeof(IRequestHandler<,>)))
            .AsImplementedInterfaces()
           .InstancePerLifetimeScope();

Is it the case that I cannot call two sends in a single context?

**Comment by jbogard** [comment]
It looks like you're not using Autofac's scopes correctly:

https://autofac.readthedocs.io/en/latest/lifetime/instance-scope.html#instance-per-lifetime-scope

You're not creating any kind of scope here? I don't use Autofac so I can't say for sure but this looks like your lifetimes are not configured correctly.

Typically, MediatR dependencies should be configured as `Transient` because they don't have any kind of state that needs to be scoped. I think this is `InstancePerDependency` in Autofac?

**Comment by Audhut** [comment]
OK.  the problem was with the for each and not the mediatR .

using a normal for each fixed it. 


      foreach (var pc in pcs)
                  {
	              var eval1 = await  _mediator.Send(new RunEvaluationCommand(pc.id1, start, end));
	              var eval2 = await _mediator.Send(new RunEvaluationCommand(pc.id2 ,start, end))	 
          }
