### ISSUE TITLE
Question: Why the Handler Wrappers?

### ISSUE THREAD

**Issue by kappy** [jbogard/MediatR#74]
Hi,

Like the titles says, this is not really an issue, but just a question. I was looking around the code (kudos by the way :+1: ) and I notices the double Generic caches of ConcurrentDictionaries to hold the generic types of both the Generic Handler and a default Handler Wrapper.

While I do understand the first, because the type of the generic IRequestHandler<> is not know and you want to save up the MakeGeneric call, I did not get to find a reason for the Wrappers, since all they do is to call the inner handler. I did not find any hook on them or usages besides the inner call.

Did I over looked something?

Thanks in advance, and kudos again for this awesome library. It has already become a standard on both my personal and my team's professional projects.

**Comment by jameshulse** [comment]
@kappy, as far as I can tell, they facilitate calling the correct method on the implemented handler at runtime. They are used to convert from the request type to the closed generic interface that the concrete handler implements.

I tried writing my own version of a simple `IAsyncRequestHandler<TRequest, TResponse> : where TRequest : IAsyncRequest<TResponse>` and found that the runtime could not call the `Handle` method on my handler with the given parameter.

AsyncHandler:
````C#
public interface IAsyncCommandHandler<TRequest, TResponse> 
    where TRequest : ICommand<TResponse> 
{ 
    Task<TResponse> Handle(TRequest request);
}
````

Mediator:
````C#
public Task<TResponse> ExecuteAsync<TResponse>(ICommand<TResponse> request) 
{ 
    var requestType = request.GetType(); 
    var handlerType = typeof (IAsyncCommandHandler<,>).MakeGenericType(requestType, typeof (TResponse)); 
 
    dynamic handler = _lifetimeScope.Resolve(handlerType); 
 
    return handler.Handle(request); // Throws runtime exception as it can't find the correct overload
} 
````

The parameter passed to `Handle` is `ICommand<TResponse>` rather than the concrete type of my request. The wrapper that MediatR uses somehow binds the call correctly but I can't help much more than that without @jbogard stepping in :)

**Comment by jbogard** [comment]
It's funny generics stuff. Basically the only way I could get the compiler to be happy.

**Comment by davidkeaveny** [comment]
@jameshulse did you come up with a solution for this? @jbogard 's generic-fu is pretty hard to fathom, especially if you have a much simpler implementation (e.g. no pipeline). All those request handler wrappers are black magic as far as I am concerned!

**Comment by jameshulse** [comment]
@davidkeaveny I'm afraid not. After failing to repeat the black the magic for myself I believe I gave up. Jimmy is a magician - it might be best just using MediatR. Good luck!
