### ISSUE TITLE
All interfaces in MediatR.Contracts

### ISSUE THREAD

**Issue by satano** [jbogard/MediatR#809]
Hello.

I have a question/suggestion. Why there are only some interfaces in **MediatR.Contracts** library? Is there a reason not to add all of the MediatR interfaces there?

Thanks.

**Comment by jbogard** [comment]
It's "Contracts" not "Interfaces" so it's only the interfaces you'd include in your contract types. The others wouldn't make sense to distribute with contracts, like in a Blazor scenario.

**Comment by jbogard** [comment]
I follow SemVer which means across major versions, some of those interfaces do break. "Contracts" is an overloaded term but what I'm referring to here are the message contracts.

Because major versions break the interfaces, there is no value separating those out. There is value in separating out the request contracts as people often distribute those message contracts as a separate assembly.
