### ISSUE TITLE
How to properly pipeline async handlers?

### ISSUE THREAD

**Issue by abatishchev** [jbogard/MediatR#98]
Given you have a pipeline or a flow of async notification handlers, say `Pre1`, `Pre2` and `Final`, of the same notification type. How to run them one after another.

Currently I use use Simple Injector to decorate Final with Prep1 and Prep1 with Prep2:

```csharp
container.RegisterCollection<IAsyncNotificationHandler<Foo>(
  new[]
  {
    typeof(FinalHandler)
  });
container.RegisterDecorator<IAsyncNotificationHandler<Foo>, Prep1Handler>();
container.RegisterDecorator<IAsyncNotificationHandler<Foo>, Prep2Handler>();
```

Instead I propose method `PipelineAsync()` with a naïve implementation such as:
```csharp
public async Task PipelineAsync(IAsyncNotification notification)
{
  foreach(var handler in GetNotificationHandlers(notification)
  {
    await handler.Handle(notification);
  }
}
```
or add an overload to existing method `PublishAsync()` accepting `PublishOptions` with a property  of type enum:
```csharp
enum HandlerRunMode
{
  // Default = Parallel, // optionally
  Parallel,
  Sequential
}

public Task PublishAsync(IAsyncNotification notification)
{
  return PublishAsync(notification, new PublishOptions { RunMode = HandlerRunMode.Parallel });
}

public Task PublishAsync(IAsyncNotification notification, PublishOptions options)
{
  switch (options.RunMode)
  {
    case (HandlerRunMode.Parallel): return ParallelPublishAsyncImpl(notification);
    case (HandlerRunMode.Sequential): return SequentialPublishAsyncImpl(notification);
  }
}
```
Makes sense?

**Comment by abatishchev** [comment]
Can you please review?

**Comment by abatishchev** [comment]
@jbogard can you please take a look?

**Comment by samueldjack** [comment]
I've just been bitten by this, and it's taken me the best part of 5 hours to work out what was going on :-(

In my case I had two handlers listening to the same event, and each handler used the same DbContext to make async calls to my database. I kept getting System.NotSupportedException thrown by the Entity Framework async methods with the message "A second operation started on this context before a previous asynchronous operation completed". I couldn't fathom it, because my expectation was that the handlers would be executed in sequence rather than in parallel.

**Comment by abatishchev** [comment]
Moving discussion to the pull request
